### ISSUE TITLE
distingushing between wilaya, daira and baladiya

### ISSUE THREAD

**Issue by khawarizmus** [badre429/dzcities#1]
Before anything, I wanted to the people behind this amazing work and effort.

While this looks like a gold mine and a very good starting point for having a solid standard for apps that rely on locations in Algeria. I find it difficult to know from the current JSON structure whether the city name is a wilaya or a baladia or a daira. can this be added sementically into the current structure? if not is there a systematic way to extract this information from the postcode for example?

Thank you

**Comment by badre429** [comment]
@gimyboya  
this data in this repo does not take DAIRA in consideration the list of all wilayas in **./wilayas.json** file and the baladiyas of each wilaya is in **./wilaya/1.json** file **replace 1 with the code of willaya**

**Comment by khawarizmus** [comment]
Thank you for the quick reply.
Does this mean that Diarat are not listed or they are listed as part of the baladiat in each respective file?

**Comment by badre429** [comment]
@gimyboya  each dayra is baladia therefore is listed on the  **./wilaya/1.json** file

**Comment by khawarizmus** [comment]
Alright I appreciate your answer. 

Thank you @badre429
